### PR TITLE
Shearing Sheep fix(es), added summon command

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
- added summon command for better bug fixing (summon is a "normal" command in MCPE normally)
- changed shearing sheeps bugfix (when a sheep was in level, the shear button was shown on every entity)
- sheeps no drop correct wool color when sheared

## Changed Branch
1.0.0-bug-fixes

## Optional information
Shearing is now better but not perfect. Somehow the handling is a little weird. But it works. In the version before, it was possible to shear wolfes etc. pp - when only a sheep was available near (ok, it was not possible, but the button was shown). Maybe, i can find another solution.

### CODE REVIEW

**Comment by Sandertv** [comment]
Does this fix the button showing up on every entity? Have you tested that?

**Comment by kniffo80** [comment]
Its better now, but it needs some more work. Yes, tested. Always ;-)

**Comment by caspervanneck** [comment]
@kniffo80 kan you improve the mobspawner

**Comment by kniffo80** [comment]
@caspervanneck i don't use the spawner. I use the summon command (which comes with this PR) to test entities. Anyway - what's wrong about the spawner?

**Comment by caspervanneck** [comment]
@kniffo80  if plache a spawner and entity is linkt and rejoin than spawner dont work

**Comment by kniffo80** [comment]
@caspervanneck That's interesting. I'll try to look at it.

So, you mean when you place a spawner and link an entity with the spawner after log out and log in back, the spawner is not working anymore? Am I right?

**Comment by caspervanneck** [comment]
@kniffo80 yes

**Comment by kniffo80** [comment]
@caspervanneck tried it by myself in creative: you are right. SOMETHING is broken ;) when I've time I'll check that!

**Comment by caspervanneck** [comment]
👍 @kniffo80

**Comment by kniffo80** [comment]
@caspervanneck i've checked the spawner on a flat world. When placing an egg in the spawner, an animation is shown and the spawner spawns the desired entity. After logging out and back in - the animation is not shown anymore. This could be a client error or is intended to do so. BUT only the animation is missing. The spawner still spawns entities. You can also change them with a spawn egg. So spawner animation seems to be broken. I've debugged the stuff and this is the result :smile: 

The only thing that can happen is that an entity is spawned to a bad location. This needs to be fixed (imho).

About the animation: i think an event is sent to the client which animates the spawner when an egg is placed the first time. That's a deeper check I need to do. The only question: is this really important at the moment? :relaxed:

**Pull request merged**
