### PR TITLE
I need @magicode1 to approve this in a review

### PR DESCRIPTION
**Pull request by jasonwynn10**
I need @magicode1 to approve this in a review for the use of pullapprove

### CODE REVIEW

**Comment by jasonwynn10** [comment]
^approve

**Comment by jasonwynn10** [comment]
approve

**Comment by jasonwynn10** [comment]
Approved

**Comment by jasonwynn10** [comment]
why are none of these working?!

**Comment by Sandertv** [comment]
+1

**Comment by jasonwynn10** [comment]
according to the pullapprove settings that are default, I need magicode to approve this before it can be merged

**Comment by jasonwynn10** [comment]
HAH! I got it!

**Pull request merged**
