### PR TITLE
Cows and Pigs are now able to breed (and can be fed of course)

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
- cows can breed now too
- pigs can also breed now
- some code enhancements

## Changed Branch
1.0.0-bug-fixes

## Optional information
- feeding a baby pig is nearly impossible - I'll try to fix this in next PR
- tested everything on my personal local and remote  server

### CODE REVIEW

**Comment by archie426** [comment]
+1 Good job

**Comment by archie426** [comment]
I would like others to test this as well, before we merge

**Comment by AppleDevelops** [comment]
EventListener is where the error occurs

**Comment by kniffo80** [comment]
Ok. Thanks for reporting. Will fix this today and Push another commit.

**Comment by kniffo80** [comment]
@AppleDevelops i added some more commits. Please try again. And be sure, that PureEntitiesX is the only plugin you use on your server! Normally, when using instanceof it should work without an additional check. And I added some more configuration - for interaction distance and search partner distance.

Thanks for reviewing this. And again: I'm not a PHP developer, I'm only experienced in C, C++ and especially in JAVA. So, PHP is not THAT different from JAVA, but still a lot of differences which annoy me sometimes :smile:

**Comment by Magicode1** [comment]
@kniffo80 that's exactly how I feel about coding Java

**Comment by kniffo80** [comment]
What I like about PHP - direct testing without recompile code again. For debugging quite nice :smile:

**Comment by archie426** [comment]
@kniffo80 Yeahhh boiii PHP is da best

**Comment by archie426** [comment]
Ok, I tested and it works, good job

**Comment by Magicode1** [comment]
+1 Nice!

**Comment by AppleDevelops** [comment]
It works now, sorry it took so long. I am sick so it took some effort to get to my laptop.

**Pull request merged**
