### PR TITLE
Removed unused spawn tasks

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [ ] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
This PR removes the unnecessary spawning tasks from the code.

## Changed Branch
master

## Optional information
Nothing more :smile:

### CODE REVIEW

**Comment by Magicode1** [comment]
+1

**Comment by archie426** [comment]
+1

**Comment by kniffo80** [comment]
And another commit - "reworked spawning position. a LOT better now." :smile: 

Tested on a server with 100% spawn rate - works quite good.

**Comment by kniffo80** [comment]
@jasonwynn10 you assigned to me - but i cannot merge. Not all checks passed. I can do it manually with GIT command line ...

**Comment by Sandertv** [comment]
+1

**Comment by archie426** [comment]
+1

**Pull request merged**
