### PR TITLE
Sheeps can now be fed and breed

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
- sheeps now stop following player when distance increases or wheat is not in hand anymore
- sheeps can now breed - feed them with wheat (2 sheeps must be fed) and they are searching each other to produce a baby sheep
- baby sheeps can be fed and grow up
- introduced a extension class for breeding (which will be used later for pigs too)
- implementation for pig should be done easily with the prework

**Beware:** I've tested this change on my own server, locally and on a remote server. I've found no bugs until now. The implementation needs some rework. I will do this when Pig breeding is implemented.

## Changed Branch
1.0.0-bug-fixes

## Optional information
Nothing - I hope I can make it even better implementation in the next couple of days.

### CODE REVIEW

**Comment by jasonwynn10** [comment]
Tested?

**Comment by kniffo80** [comment]
Yes - told already in the description ;-)

**Comment by Magicode1** [comment]
+1 Great Job!

**Comment by kniffo80** [comment]
I hope I can implement other breeding entities in time. And the code needs some more cleanup.

all: I'm doing this mainly for my 8 years old son. He's telling me a lot about minecraft PE, so that i think "maaaaan, there's sooooo much to be implemented" :smile:

**Comment by jasonwynn10** [comment]
This is awesome! Could you make cows be able to be fed too?

**Comment by archie426** [comment]
+1

**Comment by kniffo80** [comment]
@jasonwynn10  shouldn't be THAT problem as the base is there. I'll try it with all breedable animals.

**Comment by jasonwynn10** [comment]
+1

**Comment by Sandertv** [comment]
+1

**Comment by Magicode1** [comment]
I am going to go ahead and merge. Keep up the good work!

**Pull request merged**
