### PR TITLE
Fixes InvalidArgumentException during setHealth()

### PR DESCRIPTION
**Pull request by samalero**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
```
New bugfixes
```

## Changed Branch
```master```

## Optional information
```
2017-01-05 [10:00:29] [Server thread/DEBUG]: BatchPacket  0x78da93116108fcdbe754683bd569cdcea3ce364fa7396af1fc72066106461625963bccccda4c0c20cca2c4748719008a260d90
2017-01-05 [10:00:29] [Server thread/CRITICAL]: InvalidArgumentException: "Value 19 exceeds the range!" (EXCEPTION) in "/src/pocketmine/entity/Attribute" at line 175
2017-01-05 [10:00:29] [Server thread/DEBUG]: #0 /src/pocketmine/entity/Entity(705): pocketmine\entity\Living->setHealth(integer 19)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #1 /src/pocketmine/entity/Living(115): pocketmine\entity\Entity->attack(integer 1, pocketmine\event\entity\EntityDamageByEntityEvent object)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #2 /PureEntitiesX-master/src/revivalpmmp/pureentities/entity/BaseEntity(140): pocketmine\entity\Living->attack(integer 1, pocketmine\event\entity\EntityDamageByEntityEvent object)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #3 /src/pocketmine/Player(2464): revivalpmmp\pureentities\entity\BaseEntity->attack(integer 1, pocketmine\event\entity\EntityDamageByEntityEvent object)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #4 /src/pocketmine/network/Network(252): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\InteractPacket object)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #5 /src/pocketmine/Player(1800): pocketmine\network\Network->processBatch(pocketmine\network\protocol\BatchPacket object, pocketmine\Player Player(8))
2017-01-05 [10:00:29] [Server thread/DEBUG]: #6 /src/pocketmine/network/RakLibInterface(136): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #7 /src/raklib/server/ServerHandler(94): pocketmine\network\RakLibInterface->handleEncapsulated(string 195.242.114.33:19132, raklib\protocol\EncapsulatedPacket `...8..8....3x...a....Th;.i....6O.9j..r.a.F.%.;...L. ...t....&.., integer 0)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #8 /src/pocketmine/network/RakLibInterface(74): raklib\server\ServerHandler->handlePacket(boolean)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #9 /src/pocketmine/network/Network(156): pocketmine\network\RakLibInterface->process(boolean)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #10 /src/pocketmine/Server(2346): pocketmine\network\Network->processInterfaces(boolean)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #11 /src/pocketmine/Server(2099): pocketmine\Server->tick(boolean)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #12 /src/pocketmine/Server(1981): pocketmine\Server->tickProcessor(boolean)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #13 /src/pocketmine/Server(1600): pocketmine\Server->start(boolean)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #14 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/smlr/PocketMine/PocketMine-MP.phar/, string /home/smlr/PocketMine/, string /home/smlr/PocketMine/plugins/)
2017-01-05 [10:00:29] [Server thread/DEBUG]: #15 (1): require(string phar:///home/smlr/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```

### CODE REVIEW

**Comment by samalero** [comment]
i am check this mobs and server send me errors like this
```
2017-01-05 [09:51:55] [Server thread/DEBUG]: BatchPacket  0x78da931161c87abadfa9d076b7d3cea083ce47961a1f2aae2a770661064666259608666d26063056628a000080990d48
2017-01-05 [09:51:55] [Server thread/CRITICAL]: InvalidArgumentException: "Value 16 exceeds the range!" (EXCEPTION) in "/src/pocketmine/entity/Attribute" at line 175
2017-01-05 [09:51:55] [Server thread/DEBUG]: #0 /src/pocketmine/entity/Entity(705): pocketmine\entity\Living->setHealth(integer 16)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #1 /src/pocketmine/entity/Living(115): pocketmine\entity\Entity->attack(integer 1, pocketmine\event\entity\EntityDamageByEntityEvent object)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #2 /PureEntitiesX-master/src/revivalpmmp/pureentities/entity/BaseEntity(140): pocketmine\entity\Living->attack(integer 1, pocketmine\event\entity\EntityDamageByEntityEvent object)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #3 /src/pocketmine/Player(2464): revivalpmmp\pureentities\entity\BaseEntity->attack(integer 1, pocketmine\event\entity\EntityDamageByEntityEvent object)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #4 /src/pocketmine/network/Network(252): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\InteractPacket object)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #5 /src/pocketmine/Player(1800): pocketmine\network\Network->processBatch(pocketmine\network\protocol\BatchPacket object, pocketmine\Player Player(8))
2017-01-05 [09:51:55] [Server thread/DEBUG]: #6 /src/pocketmine/network/RakLibInterface(136): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #7 /src/raklib/server/ServerHandler(94): pocketmine\network\RakLibInterface->handleEncapsulated(string 195.242.114.33:19132, raklib\protocol\EncapsulatedPacket `...........0x...a.z....v......G...*.*w.a.Ff%..fm&.0Vb......H, integer 0)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #8 /src/pocketmine/network/RakLibInterface(76): raklib\server\ServerHandler->handlePacket(boolean)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #9 /src/pocketmine/network/Network(156): pocketmine\network\RakLibInterface->process(boolean)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #10 /src/pocketmine/Server(2346): pocketmine\network\Network->processInterfaces(boolean)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #11 /src/pocketmine/Server(2099): pocketmine\Server->tick(boolean)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #12 /src/pocketmine/Server(1981): pocketmine\Server->tickProcessor(boolean)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #13 /src/pocketmine/Server(1600): pocketmine\Server->start(boolean)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #14 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/smlr/PocketMine/PocketMine-MP.phar/, string /home/smlr/PocketMine/, string /home/smlr/PocketMine/plugins/)
2017-01-05 [09:51:55] [Server thread/DEBUG]: #15 (1): require(string phar:///home/smlr/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```

**Comment by Sandertv** [comment]
I don't think changing the health will fix that...

**Comment by samalero** [comment]
...or can not specify a max health. As for example in a file Zombie.php

**Comment by samalero** [comment]
I am tested this now. Now server don`t send me errors. Sorry for my bad english(

**Comment by jasonwynn10** [comment]
We can't use this because each of the mob's health have different maximums than the player. Whether it stops the error or not, we can't use this.

**Comment by samalero** [comment]
It is easy to check. I called these monsters and beat his hand once and I always showed the rest of 19 HP. But in some mobs such as the zombies do not have instructions on HP standards but they are working.

**Comment by jasonwynn10** [comment]
then try to match it to PC

**Comment by samalero** [comment]
Then why when they spawn mobs have 20 HP, regardless of setMaximumHP settings?

**Comment by samalero** [comment]
This option can not be used at all and the error will disappear, too ...

**Comment by archie426** [comment]
How can the bug be reproduced?

**Comment by samalero** [comment]
I bump API to 2.0.0 and just enter game. PocketMine-MP 1.6.1dev-#137

**Comment by samalero** [comment]
I found a workaround...

**Comment by kniffo80** [comment]
I've done that already with the entities. You have to call setHealth and setMaxHealth. It's on 1.0.0-bug-fixes branch. So i wonder why this is again applied to the entities ...

**Comment by archie426** [comment]
@kniffo80 The second resolution or the first?

**Comment by kniffo80** [comment]
The second one - setting health and maxhealth - before it was only setting max health which lead to the error. It's already in the 1.0.0-bug-fixes branch :smiley:

**Comment by Sandertv** [comment]
Well guess we can just merge this to the master branch for now, to fix that issue there.

**Comment by archie426** [comment]
Yeah, it won't cause conflicts

**Pull request merged**
