### PR TITLE
Some corrections

### PR DESCRIPTION
**Pull request by kniffo80**
- file logging is now implemented correctly
- enhanced log output in logfile for entity spawning a little bit

### CODE REVIEW

**Comment by kniffo80** [comment]
More properly? What do you mean with this?

But yes, spawning is a little to fast - in my opinion. And there should be more factors for spawning. At the moment, spawning is sufficient but can be optimized lot more ;)

**Comment by Sandertv** [comment]
It's currently lots of repeated code, but I'm sure we can find something to improve that. I just don't like code that repeats itself often :P

**Comment by Sandertv** [comment]
It's not a big deal though, and it was mainly my fault.

**Comment by kniffo80** [comment]
Agreed ;) yes - the code is very often repeated. I wrote a Mob Plugin for Nukkit and I built for each entity spawner classes that had their own logic. Anyway - I'll try to get autospawn a little bit better (with maybe less code, let's see) :)

**Comment by Sandertv** [comment]
👍

**Pull request merged**
