### PR TITLE
Solve the travis errors and add kniffo to .pullapprove

### PR DESCRIPTION
**Pull request by jasonwynn10**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
Attempts to solve the travis errors

## Changed Branch
master

## Optional information
none

### CODE REVIEW

**Comment by jasonwynn10** [comment]
Issue found here: https://travis-ci.org/RevivalPMMP/PureEntitiesX/builds/200221426#L702

**Comment by AppleDevelops** [comment]
DevTools isn't downloaded

**Comment by jasonwynn10** [comment]
@AppleDevelops that was the point of the fix

**Comment by jasonwynn10** [comment]
Fixed! https://travis-ci.org/RevivalPMMP/PureEntitiesX#L706

**Comment by jasonwynn10** [comment]
+1

**Comment by jasonwynn10** [comment]
ready to merge
+1

**Comment by archie426** [comment]
+1

**Pull request merged**
