### PR TITLE
Make Sheep can spawn & fix some bug ( i think~

### PR DESCRIPTION
**Pull request by xinghao2003**

### CODE REVIEW

**Comment by archie426** [comment]
Next time, when you PR, please make separate PRs for bug fixes and additions

**Comment by caspervanneck** [comment]
dont merge it @archie426  @Sandertv O @Magicode1

**Comment by caspervanneck** [comment]
he try it that it works on 1.0.0 o but there is a branch for that @xinghao2003

**Comment by caspervanneck** [comment]
so closes this

**Comment by xinghao2003** [comment]
ok ok

**Comment by archie426** [comment]
Please include your message in one comment please @caspervanneck

**Comment by jasonwynn10** [comment]
If people aren't going to use the PR system I added, then what was the point of it?

**Pull request closed without merging**
