### PR TITLE
Master Cleanup

### PR DESCRIPTION
**Pull request by jasonwynn10**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
* Added License Headers 
* Removed unused dependencies
* Travis changes
* pullapprove changes
* changed ExplosionPrimeEvent directory

## Changed Branch
master

## Optional information
...

### CODE REVIEW

**Comment by jasonwynn10** [comment]
I'll make the coding style consistent next

**Comment by jasonwynn10** [comment]
this should probably get merged before we try to merge in the 1.0.0 branch huh?

**Comment by Sandertv** [comment]
+1

**Comment by jasonwynn10** [comment]
+1

**Pull request merged**
