### PR TITLE
Some performance enhancements. New interactive button handling.

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description

- new handling for interactive button finding
- enhanced performance a lot with some configuration
- reworked spawning a bit - prepared for block - and skylight
- some other changes i can't remember now

## Changed Branch
kniffo80/kniffo80 -> RevivalPMMP/master

## Optional information
I'm sorry for those commit comments. We should rebase the master branch to remove all that commit comments which are VERY old. Anyone volunteers? :smile:

### CODE REVIEW

**Comment by kniffo80** [comment]
I think when this is merged - this can be closed (for now): https://github.com/RevivalPMMP/PureEntitiesX/issues/16

Wolves are tameable now and can be feed, can sit and attack the entity which is attacked by the player. And they also attack Zombies when they attack the player. Other entities will follow.

**Comment by jasonwynn10** [comment]
Somehow, I don't think u understand how to use git properly...

**Comment by kniffo80** [comment]
@jasonwynn10 maybe - i'll double check next time. I worked with SVN and (earlier) CVS only. And i know working with GIT is a "little" different. Maybe, you can guide me a little :relaxed:

**Comment by jasonwynn10** [comment]
Just follow what I said in the last comment and all the commit messages should dissappear

**Comment by kniffo80** [comment]
I'll do so. No problem. Although I created a new branch in my own repo. But as soon as this is merged, i'll remove my own fork and create an own branch in this repository.

**Comment by kniffo80** [comment]
I'm waiting for pull approve @archie426 @jasonwynn10 @Magicode1 @Sandertv 

When this is merged I can create a new branch in this repo to continue working ...

**Comment by jasonwynn10** [comment]
+1

**Comment by Sandertv** [comment]
+1

**Pull request merged**
