### PR TITLE
1.0.0 bug fixes

### PR DESCRIPTION
**Pull request by kniffo80**
- added configuration for creeper block explosion, changed Creeper entity to respect that setting
- added possibility to get instance of the running plugin

### CODE REVIEW

**Comment by kniffo80** [comment]
Need to add the following nested YAML property to config.yml:

```
creeper:
  block-breaking-explosion: false # when set to true the creeper will explode and also burst blocks
```

**Comment by caspervanneck** [comment]
ready to merge?

**Comment by caspervanneck** [comment]
@kniffo80

**Comment by kniffo80** [comment]
Yes. Tested on my own server - got blown away by a creeper when setting is **true**.

**Pull request merged**
