### PR TITLE
Cows, Mooshrooms, Pigs and Sheeps are now feedable and can breed

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
- changed implementation to reduce code complexity
- cows, mooshrooms, pigs and sheeps now can breed (and of course be fed)
- sheeps still can be sheared
- removed the age interface from WalkingEntity (which is not needed anymore)
- removed getMaxHealth from Enderman - it seem to cause problems with attribute value exceeds max value ...
- some code enhancements
- tested on my local and remote server - each single changed entity

## Changed Branch
1.0.0-bug-fixes

## Optional information
- please test before merging and report back - i tested it also, but you may know: sometimes the developer is a little bit "blind" about his own implementation :smile:

### CODE REVIEW

**Comment by archie426** [comment]
Will test later

**Comment by Magicode1** [comment]
+1

**Comment by jasonwynn10** [comment]
When the title doesn't contain the 'WIP', pullapprove will approve merging

**Comment by jasonwynn10** [comment]
can you make snowmen shearable too? they should be able to be sheared into the derpy snowman

**Comment by kniffo80** [comment]
**Added some more commits:**

- cows now can be milked with a bucket
- chicken can now be fed and breed
- chickens laying eggs now every 6000-120000 ticks
- some code enhancements
- fixed a bug where feeding a baby animal was not possible until the parent went away - now babies are feedable also when newly "born" in any case!
- added more log output
- use "info" loglevel in a productional environment!!!

**Comment by kniffo80** [comment]
@jasonwynn10 yeah, can try. wanted to have all "normal" breeding animals. Now this is done (except horses). Other animals as Wolf and Ocelot can only breed when tamed. So, next bigger thing will be taming (yeah, tried that a couple of times for Nukkit, but never worked). But I can try with a snowman too. Shouldn't be a big thing. But when time comes. Having not that much time left this week as I'm going to Oslo tomorrow - staying there for 2 days (with my company). But as soon as I've time I'll of course continue with all that stuff. This plugin is a great base IMHO. So continuing on that :smile:

**Comment by kniffo80** [comment]
And some more code changes:

- bugfixes
- when button is displayed to player the entity now stays for a short amount of time to ease interaction (we can remove that later)
- moved a lot of code from walkingentity to walkinganimal - this fixes a lot of troubles
- even more stable now
- still under development (WIP)
- will merge this when I'm satisfied :smile:

**Comment by jasonwynn10** [comment]
@kniffo80 has the animal interaction time been tested for if the setting is 0 yet?

**Comment by kniffo80** [comment]
@jasonwynn10 not tested. but from my perspective - it SHOULD work :smile: will test tomorrow :smile: and there will be some more smaller changes - but for now my couch is calling.

**Comment by NycuRO** [comment]
@kniffo80 Why you delete Spawn Animals with help name of Biomes? :/

**Comment by kniffo80** [comment]
More commits added. Will merge that stuff this week into bug-fixes-1.0.0!

- interaction now works flawlessly (had problems when more entities emerged in level, then it was nearly impossible to interact!) as far as i could test with a lot of entities in a level (approx. 25)
- moved configuration to a specific helper class
- introduced an interaction helper class which now controls button interaction
- one or more configuration properties added

@NycuRO biome check is there - take a look at WolfSpawner (for example). But not all biomes are present at the moment - so I removed biome check where it was not possible.
@jasonwynn10  tested the rest when in interaction mode with stayTime = 0 - working flawlessly!

**Comment by kniffo80** [comment]
Another final commit:

- rabbits can breed now too
- rabbits drop correct items when killed
- started with taming (only started, not useable yet)

I tested all that stuff on my local and remote MCPE PocketMine Server. No problems so far. Keep in mind that taming is not yet really started. The things found for taming are just a start - it needs a LOT of work :unamused:

**Comment by kniffo80** [comment]
... waiting for merge on this now.

**Comment by jasonwynn10** [comment]
+1

**Pull request merged**
