### PR TITLE
Poggit icon

### PR DESCRIPTION
**Pull request by Magicode1**
This PR adds an Icon for the plugin release on Poggit.

### CODE REVIEW

**Comment by archie426** [comment]
+1 Good idea

**Comment by Magicode1** [comment]
+1

**Comment by Sandertv** [comment]
Could I ask? What does this exactly do? Just curious :)
+1

**Comment by Magicode1** [comment]
It's the icon for the Plugin Release on Poggit. The Release section is almost done :)

**Comment by Sandertv** [comment]
Oh cool! I wasn't aware of that!

**Comment by SOF3** [comment]
Check. It is a JPEG!

**Pull request merged**
