### PR TITLE
Creepers and Spiders can jump now, some little stuff

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [ ] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
- reduced creeper code a little, creepers can now jump too  …
- reduced spider code, they can now jump too
- some little bugfixes
- renamed "summon" to "pesummon" - some servers already have summon command

## Changed Branch
master

## Optional information
As ever: I've tested the changes especially when it comes to creepers and spiders. I reduced the old code a little and tested bombing and follow of creeper. Also tested if spiders are able to jump now. Additionally I introduced a new variable $attackDistance - which was needed. Otherwise the entity could attack from a far far away distance :satisfied:

### CODE REVIEW

**Comment by jasonwynn10** [comment]
Is anyone else getting annoyed by the amount of commits in the list even though most aren't relevant?

**Comment by AppleDevelops** [comment]
@jasonwynn10 You aren't the only one

**Comment by kniffo80** [comment]
Same for me ... Can't we delete specific commit messages in a pull request?

**Comment by archie426** [comment]
Anyway as long as this works, it is alright....
+1

**Comment by jasonwynn10** [comment]
@kniffo80 That is the reason for the check boxes in the template. Don't use your master branch for making pull requests into ours, or all the commits come with it

**Comment by jasonwynn10** [comment]
+1

**Comment by kniffo80** [comment]
Aye aye @jasonwynn10

**Pull request merged**
