### PR TITLE
New directory structure

### PR DESCRIPTION
**Pull request by 95CivicSi**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Updates to Directory Structure and Poggit Info
...

## Master
...

## This should make testing and deploying the plugin directly from source easier.  Plugin essential files/folders are moved into their own sub-folder.  This leaves all non-essential files/folders in the root directory.  Poggit files are updated to reflect RevivalPMMP instead of Poggit-Orphanage (we love you guys but.....). This includes fixes in the readme.

### CODE REVIEW

**Comment by Awzaw** [comment]
I don't see how this makes it easier to run from source, this change means we now can't just git clone the repo from within the plugins folder like every other plugin (except EconomyS which is also a PITA for this reason), and you can't git mv the actual folder into plugins... I always rename cloned repos with SRC suffix to avoid adding config files, but this change means I'll have to work on a copy of the repo.

**Comment by 95CivicSi** [comment]
@Awzaw, this was done before I had some significant exposure to how PhpStorm works.  I wasn't familiar with the integrated git features or the ability to run PocketMine-MP directly in the IDE.  While I still haven't reached a point of being able to run PocketMine-MP directly in PhpStorm, I understand your point and agree.  I'll have this changed ASAP.

**Comment by Awzaw** [comment]
Thanks, hopefully there'll be a new release soon on Poggit soon?

**Comment by 95CivicSi** [comment]
IDK about a release yet.  There are some things (like #245) that need addressing.  I'm could use some advice if you've got time.  Hit me up on Discord.  https://discord.gg/6Kcx3kK

**Pull request merged**
