### PR TITLE
Merge 1.0.0-bug-fixes into MASTER (finally)

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
* this is my merge from 1.0.0-bug-fixes into master.
* I've tested the code locally (started the server, played around a little with the entities and so on)
* README.MD was a little difficult to merge - please check and change after merge perhaps

## Changed Branch
master

## Optional information
Finally when everything is merged into MASTER we should delete the 1.0.0-bug-fixes branch. And all other branches should be synced with the master branch! This should be done regulary - especially when the branch gets older and older :smile:

### CODE REVIEW

**Comment by kniffo80** [comment]
I don't know why travis fails - the latest master PocketMine-MP works fne locally with my changes ... Can someone inspect? Ah and close https://github.com/RevivalPMMP/PureEntitiesX/pull/110 please! This is irritating!

**Comment by archie426** [comment]
+1

**Comment by Sandertv** [comment]
+1

**Comment by archie426** [comment]
@kniffo80 No idea why that happens, I think it is because of PMMP jenkins server
Just to check, can this be merged?

**Pull request merged**
