### PR TITLE
Last changes on 1.0.0-bug-fixes

### PR DESCRIPTION
**Pull request by kniffo80**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
more on tamed wolves

## Changed Branch
1.0.0-bug-fixes

## Optional information
This will be the latest change on 1.0.0-bug-fixes - all other stuff will be done when everything is merged into the MASTER branch (i think).

### CODE REVIEW

**Comment by Sandertv** [comment]
+1

**Comment by jasonwynn10** [comment]
Thank you for that

**Comment by jasonwynn10** [comment]
+1

**Comment by archie426** [comment]
Can this be merged?

**Comment by kniffo80** [comment]
It should be merged :smile: and after merging the stuff into 1.0.0-bug-fixes it should be merged with master. Then I will continue to work on taming the wolves and some more stuff.

**Pull request merged**
