### PR TITLE
1.0.5 Update.

### PR DESCRIPTION
**Pull request by NycuRO**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
...

## Changed Branch
...

## Optional information
...

### CODE REVIEW

**Comment by Sandertv** [comment]
+1

**Comment by kniffo80** [comment]
Which branch?

**Comment by NycuRO** [comment]
@kniffo80 Is to master... Please don't accept.

**Comment by NycuRO** [comment]
But one problem and i don't seen file:

```[17:20:57] [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Class pocketmine\network\protocol\AddEntityPacket not found
[17:20:57] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\network\protocol\AddEntityPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[17:21:12] [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Class pocketmine\network\protocol\AddEntityPacket not found
[17:21:12] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\network\protocol\AddEntityPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
```

**Comment by kniffo80** [comment]
Because 1.0.5 is not ready yet by pocketmine? Only on a branch?

**Comment by archie426** [comment]
+1

**Comment by kniffo80** [comment]
I have a local version compatible with 1.0.5 (api3/network branch) - i can push the changes if you all want.

**Pull request closed without merging**
