### PR TITLE
make horse ridable

### PR DESCRIPTION
**Pull request by caspervanneck**

### CODE REVIEW

**Comment by Magicode1** [comment]
Have you tested this?

**Comment by caspervanneck** [comment]
yes it crast do syntax

**Comment by Magicode1** [comment]
It crashed the server?

**Comment by caspervanneck** [comment]
yes

**Comment by Magicode1** [comment]
We dont want anything that will crash the server! 😃 Try fixing the bug that caused it to crash, then make a pull request once it is Stable and bug free 😁

**Pull request closed without merging**
