### PR TITLE
Entities can now jump normally

### PR DESCRIPTION
**Pull request by Skull3x**

### CODE REVIEW

**Comment by Skull3x** [comment]
I recommend following the same method for swim updates, you have an example from the Squid in Genisys here.

**Comment by Sandertv** [comment]
Awesome, thanks! And yeah, don't worry, PMMP had the squids implemented too :)

**Comment by Sandertv** [comment]
Great, it works well! Now we just gotta make sure they don't jump up walls higher than 1 block. :)

**Comment by Skull3x** [comment]
I'll see what I can do :)

**Pull request merged**
