### PR TITLE
Damage reduction

### PR DESCRIPTION
**Pull request by jasonwynn10**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
This PR takes armour into account when dealing damage

## Changed Branch
Typehints and return types were added for alpha7 compatability

## Optional information
None

### CODE REVIEW

**Comment by jasonwynn10** [comment]
Can someone remind me why we need travis? Poggit does build tests for us already

**Comment by samalero** [comment]
```
PocketMine-MP Crash Dump Mon Aug 7 00:21:34 EEST 2017

Error: Cannot override final method pocketmine\tile\Spawnable::getSpawnCompound()
File: plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/tile/Spawner
Line: 0
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[1] <?php
[2] 
[3] /*  PureEntitiesX: Mob AI Plugin for PMMP
[4]     Copyright (C) 2017 RevivalPMMP
[5] 
[6]     This program is free software: you can redistribute it and/or modify
[7]     it under the terms of the GNU General Public License as published by
[8]     the Free Software Foundation, either version 3 of the License, or
[9]     any later version.
[10] 

Backtrace:

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: 44f1dedbf866f0f200d68a3789e3672c430150dc-dirty
uname -a: Linux DESKTOP-UV0DT1Q 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64
PHP Version: 7.0.21
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
DevTools 1.12.1 by PocketMine Team for API(s) 3.0.0-ALPHA7
AntiSpamPro 1.4.0-dev1 by awzaw for API(s) 3.0.0-ALPHA7
ASR 2.0.2 by iJoshuaHD for API(s) 3.0.0-ALPHA7
CustomAlerts 1.6 by EvolSoft for API(s) 3.0.0-ALPHA7
DropParty 1.0.3 by HotshotHD for API(s) 3.0.0-ALPHA7
EconomyAPI 5.7.1-dev2 by onebone for API(s) 3.0.0-ALPHA7
EconomyJob 2.0.4-dev2 by onebone for API(s) 3.0.0-ALPHA7
EconomyLand 2.1.0-dev2 by onebone for API(s) 3.0.0-ALPHA7
EconomySell 2.0.7-dev2 by onebone for API(s) 3.0.0-ALPHA7
EconomyShop 2.0.8-dev2 by onebone for API(s) 3.0.0-ALPHA7
FactionsPro 1.3.10-dev2 by Tethered_ for API(s) 3.0.0-ALPHA7
ManyWorlds 2.1.0 by aliuly for API(s) 3.0.0-ALPHA7
PEXProtection 0.1.0 by RevivalPMMP for API(s) 3.0.0-ALPHA7

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWgtv48iR/isNO0BmAlHWyy9tfAfD9uxOzl4rticTZLUYtMiWxDXJ5rJJy9rc/vd8Vd3NhzyL
mSQGLrfAeMV+VNerq74q8u97ZZyqvenwcDAaHE4mp5PenioKXexN/75XbnNM7V19uri9mb2/vvp0
dXd3e7fX20uVMXJFcxcyy3Qp9BM2xZESyziTiUhVudaRyHX4qMo0ztR8XsYJ/t7ncpPJRaKm05Uq
+elCp7musujNWxBeYhWo5km1ijNzMKsKdZWVcRkr89cglaZUxYEpwoNCPcVPMsnTND/IsUi5RQd0
zAHTVQXoJTh7bzr4tedI7k3LolK9vVBHiiQc4rA//ne+zrF2hN/43xj/O/iDEJ2zp+JGL8T5ezFj
MmKpCzG7uZlh/QTrBf670Pm2iFfrUry5eCtGg+GxuLNcuoWHlv6RW/+wjo3IC70qZCrwcwkphNHL
ciMLNRVbXYlQZqJQUWzKIl5UpRJxKWQWHeDwVEfxcgtyx44cpqBEVYhyrQTUlBqhl/zw7fcfxLcK
+oBhZtUiiUNxHYcqM0pIcEAjZq0isSByJ44cbXxHHN07jsQ7MpIsY531hIoxXwgY3eBZjP1Rjm5P
aFL+qaMls61IZNls6GNyOCB1wDBlIUPY4ocfe3sryyUZJpPklXsz9qAbWDFgHToCmBn2j/qjSD1h
cFHFSQQrw8iFLnWoQWE4HPf2ZB5j5bg/6A+C8+vZd+fHWL2KSwxOJsthpKLF8uToaDlYjgaD6OhE
jo9PTtX46HgUTsYDXIkoDKK4KEkxhXxM4gV2Dvon/QEGKsfidZxVz+Ly6v5/Hm5nwYe/DC4fhn8W
k/4Eh07GwU0cFprMKvaHrYePUPilCsV4KIaT6WQ0PRyL2f0D+c1EPJ8cfTqa4AxyzOneMQQYDfH4
i8oiL5Cd/aSNZwED/JDwQ+3xhrR5qZ4etE5MS7P1UFepw1GfTpIVLnCB9T+0TCAelEz3fnR6/aGr
WAwrvtmRv2ORysGvsaYloS/bA6mk21izMZ+3GEq0JDnvH87vHj6Q2TdqYeKS2F6XZW6mBwew4rpa
9EOdHjQMHtQ0IP457i4CQTordEvs9mhXcrIX/GlHern5RW6+RualTMzXCs1E53MJXgx4gdfO513G
nAZmt/cPH2/vri87OmDp7u/aUt3fdaQZkcd0BYn/pM26kt9dvrYwNeH5PL65mF1BlPu7+fwaEtgQ
/E8Zs6Z2QDJB0IvKlDo9T1RRtt23M7wTF7qCXz3phILYa8vd5mA+3+HnC0JD5s1m01dgjcj3y0cS
9bLQ+UxSuGld03qsK+SgP+6K+Z0uzVqXr2/fCBzkxAGuaIuZL3roVagznW7PZ+9b4rQG2/Ic9o/7
Q7p9O06rM7XAv9cWyZGdz5VlB7Tn8w5rXyvdn/TipXQ0uHsbJ68sXVuT/4SkP+lFLall82slvZaU
e3ZF5dGurEMbR//vZU3AWy2sY/Rrpb1XSfJSWh7dtezxf4a0BrzV0jpGv1ratc4/Iy2N7kp78h8i
LXhrpLWMflHadzIk+Gq6iKA92o2x4/7wc678oAj8qujTa4elFifzuXu4oamvkO0GIPujLpKonSRb
gy/u6A7MSeIq2b46zmGq83kKPjbMx3z+tQLNrv4KPZSKtdCuCDrjbbEGL8VqF2CvLFuL9HzeYepr
ZSSILlH8KVRG/jBVQJ4+AGEOIIHCEwv3Z/UTasxsGa8EVcnzYp7t36D4Oq9W4lgMBtPRcDo6EldX
too4pgWpLqOz+5vru/+d3dCzpR+QKj8znOuiPBueDscjGlxhEapMdTZgSvI5yBO5BatnhzxiqMgO
8lrss9GYxzdrCBigpiztTqvd4OdKFdszaKcZKnB93Qh1EaosVO6MQIbrWD2pFHW98UuSRG+CZUIl
9pleLhseZBansJxbZ8dSvfADqNVBuBbHbV3LIgp1UT/nT7lbj8J6GYdVUm7PxqwIrkpLXQRGlWWc
rcwZDSfgL7GqZN9uxoxSUWsJdVHOLq/enX+4fqBRErufS2OwLTr7A/8H8apSB0Y+KcfFU6w2AZX+
Emo5O6EhKvnqjkp/mybkHYKcTYTsGFXB9Tn7h21RtMtn9hjxsFYo/L0kgip7qtwRXA1+yJKaDtTR
WSgRZ2FSoUjGD/HCMy21e50qV/zvUjVySY0AipWGOxmLQslH6msUjpqIl7aPEfMZsEYBV0LAYNLf
q01N8CBSSwmLGLHR2e9LIfNcyUKQzlKIHMI3thABbFAjhaTfrFUmqnxVyAgE+kTSerolOKUHsf+w
LhR8FYPgBnhhVcmVEtQcYvW5e2GosZVonBL/wgq2my/WKnTydLeCEV/ZqKy/iR/jXEWx7OtidUBP
B9cw6ye9/PT+/vbT0fg0GH2ifazSmtRUzPeqx2K+Zw/7uOasI0oNrrJIQGJBbSHSdlnIzFCDJbLT
rFvmF7zglyrZxMhkcajEGkgoYaOnTNpej+ZYKt55AnVYGWm6S7bbRxzNq8FkNKS/40P6Oxnw71F7
RLSGTvhvyH8l/42ape638jKe0w0XFDkglnDtC/EUS/FnCh68iMNI4OZazO4DBGyEpItgNMRzPFs/
kI6YqAy8HOEdfsbqAupwvUqr/GYqgA4X2rT1sX/FYcvTghoFBRDq4cHliOXFVjhH5Q0uzNXzU8EJ
xhk0hgV1Br+VUSQKZax7E7tw6EewJU1VcASk7uBCkW5gTfVzJROy8yp+wlqkoEqJN+5YBP63TN6e
iRCrKKgHcJTVShVTzNvTv6/SBZwEN/fcbLPwQZpHXK3iEXe1b1d8MNAPXQIvLq1bFwBcFTwO601P
cNwTLj5yYxAlPDRouCtICkK+o7G0ynBJaYmjfs8+Cblwkwv9jPhdKqgCYvF9ymr2SMOepfdLCgi0
iC5+T8Tl76HDsuB9kaI8xI6+s1u8gRSwvBhZ3bAkgZN2yrR8eKAUUWxdcPg20Quomtt1dgK+mcYl
hcNUreRiW4I1cW9ZGjATsSGT++AC+TYxs8jqF5TALCVvEcNaWsZwI0RIpIuMiXEv2J1pXQJiVezQ
Kw2JqN3O+uOTVsxowMxNxcALI/Y5NZSIcTL6fyAGAasvCEFJ+98UwpQ6Zz5cnKz5cvSMwLWj7Kyi
his617M2GZweNdzNVBFrzpB0aw0dHHJecFzWN3OIAxGcIuuDvCbArVH+TrqcojMEv4reo1Bs/01V
WxUDaiWcbig22GWWuqWCm9rcfB/G7Dm3FHgo/fKm/ssNpAiHi6HWXIWUpQ0riri2erd7a1GgW5Wb
RuTxwMls3v4GW04D40YDK1ks4B9BqJPE4kp7Gz+raXY4YsntEm4XvR+RWcWooM0NcFMFP3nb83Hk
haM4T7Fxebn0ESVtfLAvbm0i5id4y1pXSVSzEiPubDLRsG99W+TMPUQ9GgwaacX+O74zL2Ir+5Gl
UQu3LHTqg7Td7VYE7Yi2Y2kI5Az60k0+4107uwn1h+sqezTeCjcSwbpKkbD4ZZMHqCSfsNjd3qjm
KPIkR91dKcEkA4JmFQLwpMXspbaTuxalfEL4ztKxi70PWWpu4auKz/ktCFGMKK8A5yz+UJpqQYQv
kqR/mSrJVC0ICh9KbLJdyBKVD6EfScgdORaO54Ib31kLtN2sjWgLVaddp+D9dhz0cxQzim1J1Hsi
GLY836ZXPjooPTuIS4dHPig1SZ1LGsqmkbUzgVGGPrQbg46zvvgOdRrUfgaEDw+/mH3oYS+4WCB8
beKoXNtE4AJDfUDAB0zFcY1CGoRiWEWtxX1xHuEKrmWyPEABY4FTpOCG7jAcK6gKJ+u37nALBrSo
daDeM11YAl8y6dlwQGd/jDMgYkgHr1J8SQlXfJhlM49KmnKEgBdt2iB3MNEqz/LADXTRIFedalGt
vE9oF3sF5aGCvV89q7CyIIuCF70K7NezhtyEkVO+zvtxFhM7QyemX+Ov8EdZZBT7W7upXnPRnig5
Ij0RIRORYM3KVOJCp7BySTotqow+H6DbD8FSjgSg7BOHPRDyZkG8DNxoW81AdP8lhoTkXHImEM+a
8ACeJaMQ7IC9rZGsjwzbsNyIA4SissKVOViF3q3AUmTauJtLfY5TU1/FacB8cmZfXykP8zmaRbKU
qGWffBVJv+s2BU225KEXeogMSpZe1xDQNpU8gmKsCo/j/G1yBYVTPs90mMS54L1wrxtoOZTkW6l+
8jWAqRTdeNwcQ1X3AhXeI1UMcbhmA1LVvoVr2Bo9YTslvLk2he2heJqW1Y562hyTZY09xtbuxmqH
yhKnHVMfzKRIRy3eX5FlFHulZCZ2ro3vuOyU9coXYoL9srStDV7somZlXHEYgmrpAqfbFNhNU5HD
f57ixJWnnesdoo5GfnIkOfIwBoKKKNKUFG1GA4dVKDtaKGT9hHo9NOPwT+NAnQmPOH3Rdk8hn+7C
QhrVOvLNEGH2M2f1xAgTw89NqDLsv3Vh36g2L+5SPRB1ajJ4QyukOnsm+a5VHTd3mq4PpRMu4QnS
W/PJZCO3xtJ3lHYMaBOpSyNN/HPqdSA9I3sku6Cj51d1emWf7Va5CvI81YhYXBkyqqH0xZnSS0k6
ImZtEY0bTg8Oooj9O0Ysre3sVZmyjZeFsuQWakkpj/uQlBrJYpa+jR/cn+yAH5gWQUVI4jumLpOi
1kK+9Z/VWEhUQ25ORUv+GMrn3zpbLquEF2pTJtuAImIcWhzDzYWCGlkli+BF/klTdW9xrpGp4ntv
4yehG4//OjDGGo100xgNyFDIXf3CAiHjksZ/dlU7+A3dyoI+OOLeDQdiaLje7vzVqnBscwL1hYMq
R0hW7cZQmChpz+KedCf7XPJ5LipRLCJPsKkMNwupPhVORuE7Fx7/8aauBsR+gAu3L1YF8mVXU02L
pFFW/6W2XKrbyJg7YD9XyuZfeJaj4OIUzwQGjjIVJ/8ixVznVVJTdE+EwF4Qp38cQoLcp03bcg/Y
l8mLbU0Dt8vIK+vxYR3VKGtOhS9+vGvBNlmVT8VpUxPZ68GRzyMWRxX0jgcuKdiOPw449BiDjq2H
3ahMFzFupF/GbxEowtqu2NRHVWrkwWZrYcctzHSe6+/WS/BCNy+gvu3uWJ2MdsaBquJsqdvpFkko
sK3iZu1ak5cyQ336vrEf1+0pmelsm1L9zBfbwCimJQW1BtwC0SxgaRjFyNWqUCvXqas7olRl0Td4
j78tqmWJSJp+6w0ECpmOWu3lcx7ykgpcy66YtnChg3XtGorHdUcn+xf0/oBb2CrROQGEHnJLvpY9
DEM0ataXTS0DgLVUBerNgDJERmCRltWgsyK7IrS06PlvE1tgtEL9ZkqbZHwgd/SsVe0Cf8ZLI1px
d62I+NrCKg5/Em3a5GsKMhqlNTqXgb3b5TvF/dYxbmr3HK/aL+Bcl2LZuu4G2IDXht04o/TK3f/+
9uFqSi+S7CjHSKr7XTHqQiQ1tVHFR1yIxcuaEgp1yNMgx06xwARdZmgnHCRF4BSvs6tnSTjRP1LV
AF6dAafekjVap5bfVPzAwB0Apcc9wB89aZscG+TYfo/FItXfNnOnyb8M5Crsc1CD8TzjIMO1Jykz
hclicOzgYkcKdzKz4X4LeoNIUdWhg+bUqXh3ff4wHX1z3Ds8fR72xs/j3uib4TcRcJ1NMG/KQuEB
aeDsZGBzkX2aHL51LxHVcwkUT+UcvVe/AFhpf2RKLtt+zsPuvPk5iUs17nyXar+MrZ8XIXDyuj1C
76KySBadMfd5eTNQFUn7eRknCCedkbLzPewq6jylnck1Aqj9VA4PP5nmK0/6fn1h352116dhsc3L
jqTAk+C5c8j97LqrnKzs8JxuoR/+Stf9EoeYGo7oOxIR0Iv5w8FkcIyfv3sPEy8Ow8PTwVE0ORwp
+nU8HsnT8WJwOFyOT0bHajA6npwuTsbid6A9W7MC/ceduTbxc4cZ15PkT4Ttd5B3apn4Tyhagq1T
3dGV4aBuXggSt0dK/agyoIKORT6iJEOw5c8vxszWVvKLaeJycHdBX1z/Euf22+Jx/xCPf6OEeztj
CNCQ+vXXfwCj3KnN
===END CRASH DUMP===
```

**Comment by NycuRO** [comment]
@kniffo80 About PR?

**Comment by NycuRO** [comment]
wtf why @jasonwynn10 ?

**Pull request closed without merging**
