### PR TITLE
Update Devtools Phar for Travis build

### PR DESCRIPTION
**Pull request by Magicode1**
Yes, we are still alive.

This fixes Travis failing (Hopefully, you know how travis can be sometimes :yum: )

If Travis doesn't work, I will continue to make changes until it does on this branch :)

### CODE REVIEW

**Comment by Magicode1** [comment]
+1

**Comment by Magicode1** [comment]
Yusssss 
/me Fist bumps the air

**Comment by Magicode1** [comment]
+1 

We are ready for merge :smile:

**Comment by Magicode1** [comment]
I removed PullApprove because it seems that not a lot of activity is going on here

**Comment by kniffo80** [comment]
Sorry been busy lately :/

**Comment by jasonwynn10** [comment]
All is fine 😃

**Pull request merged**
